name: formease
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  printing: ^5.14.0
  font_awesome_flutter: ^10.5.0  # Optional: If you want FontAwesome icons
  http: ^0.13.6
  path_provider: ^2.1.5
  intl: ^0.18.1
  permission_handler: ^10.4.0
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#1A1A2E"  # Background color (matches your theme)
  image: assets/app_logo.png  # Your app logo (add it inside assets folder)
  fullscreen: true  # Makes it full screen
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: TiroDevanagariHindi
      fonts:
        - asset: assets/fonts/TiroDevanagariHindi-Regular.ttf
